In [1]:
import pandas as pd
df = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]], columns=["A", "B", "C"])

In [2]:
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [7]:
# applies each function to the data in each column. 
# Result is dataframe with index the names of the aggregation functions
def second(x):
    return x[1]
df.aggregate(["mean", "sum", "min", "max", lambda x: x[0], second])

             A     B     C
mean       4.0   5.0   6.0
sum       12.0  15.0  18.0
min        1.0   2.0   3.0
max        7.0   8.0   9.0
<lambda>   1.0   2.0   3.0
second     4.0   5.0   6.0

In [8]:
rain_f = pd.read_parquet("data/iowa_rainfall_daily.parquet")
rain_f.columns

Index(['date', 'lon', 'lat', 'precip_in', 'precip_3d_sum', 'precip_7d_sum',
       'precip_14d_sum', 'precip_30d_sum', 'year', 'month', 'day_of_year',
       'week'],
      dtype='str')

In [47]:
import numpy as np

def gen_df(rows=2):
    cols = ["A", "B", "C", "D"]
    binary = np.random.binomial(n=1, p=0.5, size=(rows, 1))
    data = np.random.normal(loc=0, scale=5, size=(rows,2))
    uni = np.random.uniform(low=-10, high=10, size=(rows,1))
    return pd.DataFrame(np.concat((binary,data, uni), axis=1), columns=cols)

dfs = {f"label{i}" : gen_df() for i in range(5)}

df = pd.concat(dfs, names=["index 0","tomato 1"])
print(df)
df = df.reset_index(level=1)
print(df)
df = df.reset_index(drop=True)
print(df)

                    A         B          C         D
index 0 tomato 1
label0  0         1.0 -3.765990 -12.311723  0.182515
        1         1.0 -2.242000   2.255287 -0.682995
label1  0         1.0  6.641794  -2.515211  1.638616
        1         1.0  3.738525  -1.660147 -9.907950
label2  0         1.0 -2.997544  -3.348095  1.081584
        1         1.0 -4.705239   2.681312  9.415271
label3  0         1.0 -3.768737  -2.511740 -0.214337
        1         0.0 -5.760632  -3.270355  1.112186
label4  0         1.0 -0.877264   7.955332  3.318584
        1         0.0 -3.946200  -7.379108 -5.288230
         tomato 1    A         B          C         D
index 0
label0          0  1.0 -3.765990 -12.311723  0.182515
label0          1  1.0 -2.242000   2.255287 -0.682995
label1          0  1.0  6.641794  -2.515211  1.638616
label1          1  1.0  3.738525  -1.660147 -9.907950
label2          0  1.0 -2.997544  -3.348095  1.081584
label2          1  1.0 -4.705239   2.681312  9.415271
label3          0  1.0 -3.768737  -2.511740 -0.214337
label3          1  0.0 -5.760632  -3.270355  1.112186
label4          0  1.0 -0.877264   7.955332  3.318584
label4          1  0.0 -3.946200  -7.379108 -5.288230
   tomato 1    A         B          C         D
0         0  1.0 -3.765990 -12.311723  0.182515
1         1  1.0 -2.242000   2.255287 -0.682995
2         0  1.0  6.641794  -2.515211  1.638616
3         1  1.0  3.738525  -1.660147 -9.907950
4         0  1.0 -2.997544  -3.348095  1.081584
5         1  1.0 -4.705239   2.681312  9.415271
6         0  1.0 -3.768737  -2.511740 -0.214337
7         1  0.0 -5.760632  -3.270355  1.112186
8         0  1.0 -0.877264   7.955332  3.318584
9         1  0.0 -3.946200  -7.379108 -5.288230

In [46]:
df = pd.concat(dfs, names=["index 0","tomato 1"])
grouped = df.groupby("A")
print(grouped["B"])

<pandas.api.typing.SeriesGroupBy object at 0x154d9fb60>

In [48]:
df = pd.read_parquet("data/iowa_rainfall_daily.parquet")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8461430 entries, 0 to 8461429
Data columns (total 12 columns):
 #   Column          Dtype
---  ------          -----
 0   date            datetime64[ms]
 1   lon             float64
 2   lat             float64
 3   precip_in       float64
 4   precip_3d_sum   float64
 5   precip_7d_sum   float64
 6   precip_14d_sum  float64
 7   precip_30d_sum  float64
 8   year            int32
 9   month           int32
 10  day_of_year     int32
 11  week            int64
dtypes: datetime64[ms](1), float64(7), int32(3), int64(1)
memory usage: 677.8 MB

In [26]:
import numpy as np
mu, sigma = 0, 0.000000001
x = np.arange(10).reshape(-1,1).repeat(10, axis=1)
y = x.transpose()

print(x)
print(y.transpose())
print(y)

x = x + np.random.normal(loc=mu,scale=sigma, size=x.shape)
y = y + np.random.normal(loc=mu,scale=sigma, size=y.shape)
print(np.allclose(np.diff(x), 0))
print(np.allclose(np.diff(y), 0))

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9 9]]
[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9 9]]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
True
False